# Generated by Django 3.2.6 on 2021-11-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_color',
            field=models.CharField(default='#2E4D54', max_length=20),
        ),
    ]
