# Generated by Django 3.2.6 on 2021-11-19 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_charactername_character'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='actor_following',
            field=models.ForeignKey(default=899, on_delete=django.db.models.deletion.CASCADE, to='movies.crew'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_user',
            field=models.ManyToManyField(related_name='blocking_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='introduce_content',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='to_chatting',
            field=models.ManyToManyField(related_name='from_chatting', through='accounts.Chatting', to=settings.AUTH_USER_MODEL),
        ),
    ]
