# Generated by Django 3.2.6 on 2021-11-19 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_charactername_character'),
        ('accounts', '0003_auto_20211119_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crew_following',
            field=models.ForeignKey(default=899, on_delete=django.db.models.deletion.CASCADE, to='movies.crew'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='actor_following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.actor'),
        ),
    ]
