# Generated by Django 3.2.6 on 2021-11-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_charactername_character'),
        ('accounts', '0004_auto_20211119_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='actor_following',
        ),
        migrations.AddField(
            model_name='user',
            name='actor_following',
            field=models.ManyToManyField(related_name='actor_following_user', to='movies.Actor'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='crew_following',
        ),
        migrations.AddField(
            model_name='user',
            name='crew_following',
            field=models.ManyToManyField(related_name='crew_following_user', to='movies.Crew'),
        ),
    ]
