# Generated by Django 3.2.6 on 2021-11-19 07:24

import accounts.models
from django.db import migrations
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211119_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default=django.utils.timezone.now, upload_to=accounts.models.profile_image_path),
            preserve_default=False,
        ),
    ]
