# Generated by Django 3.2.6 on 2021-11-19 07:24

import accounts.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=accounts.models.profile_image_path),
        ),
    ]
