# Generated by Django 3.2.6 on 2021-11-21 05:35

import accounts.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=imagekit.models.fields.ProcessedImageField(default='images/profile/degault.jpg', storage=accounts.models.OverwriteStorage(), upload_to=accounts.models.profile_image_path),
        ),
    ]
