# Generated by Django 3.2.6 on 2021-11-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_profile_img'),
        ('accounts', '0011_auto_20211122_1639'),
    ]

    operations = [
    ]
