# Generated by Django 3.2.6 on 2021-11-23 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatting',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='saved_user', to='accounts.user'),
            preserve_default=False,
        ),
    ]
