# Generated by Django 3.2.6 on 2021-11-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='profile_path',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='crew',
            name='profile_path',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rank',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
