# Generated by Django 3.2.6 on 2021-11-21 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_charactername_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactername',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_character', to='movies.actor'),
        ),
    ]
