# Generated by Django 3.2.6 on 2021-11-18 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211118_0941'),
        ('movies', '0002_auto_20211118_0948'),
    ]

    operations = [
    ]
